#!/bin/sh

# printf "enabling cronjob...\n"
nvram set cron_enable=1
# printf "setting cronjobs...\n"
nvram set cron_jobs="0 5 */7 * * root /tmp/rc_startup"

printf "setting DNSmasq options...\n"
nvram set dnsmasq_options="
server=103.86.96.103
server=103.86.99.103
addn-hosts=/tmp/hosts
"

printf "setting static DNS addresses...\n"
nvram set wan_dns="10.0.0.1"

printf "setting startup script...\n"
nvram set rc_startup="
curl -fsSLo /tmp/rc_startup https://raw.githubusercontent.com/wwmoraes/dd-wrt/master/rc_startup
sh /tmp/rc_startup
"

printf "saving NVRAM...\n"
nvram commit

# run
printf "running startup script...\n"
sh /tmp/rc_startup
